name: CI
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Intro
        run: |
          echo "Intro to Release"
          which python
          python --version
          which pip
          pip --version
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          pip install flake8
      - name: Lint with flake8
        run: |
            # stop the build if there are Python syntax error /undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings.
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Packaging the python applications
        run: pyinstaller --onefile SimpleMonetaryTracker.py
      - name: Create Release and Upload executable asset
        id: create_release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}